# TCL File Generated by Component Editor 17.1
# Thu Aug 09 23:06:06 CEST 2018
# DO NOT MODIFY


# 
# DarkRoom "DarkRoom" v1.0
# Simon Trendel 2018.08.09.23:06:06
# decodes htc vive lighthouse signals
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DarkRoom
# 
set_module_property DESCRIPTION "decodes htc vive lighthouse signals"
set_module_property NAME DarkRoom
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Simon Trendel"
set_module_property DISPLAY_NAME DarkRoom
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DarkRoom
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DarkRoom.v VERILOG PATH DarkRoom.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter ENABLE_AVALON_INTERFACE INTEGER 1
set_parameter_property ENABLE_AVALON_INTERFACE DEFAULT_VALUE 1
set_parameter_property ENABLE_AVALON_INTERFACE DISPLAY_NAME ENABLE_AVALON_INTERFACE
set_parameter_property ENABLE_AVALON_INTERFACE TYPE INTEGER
set_parameter_property ENABLE_AVALON_INTERFACE UNITS None
set_parameter_property ENABLE_AVALON_INTERFACE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_AVALON_INTERFACE HDL_PARAMETER true
add_parameter ENABLE_SPI_TRANSMITTER BOOLEAN false ""
set_parameter_property ENABLE_SPI_TRANSMITTER DEFAULT_VALUE false
set_parameter_property ENABLE_SPI_TRANSMITTER DISPLAY_NAME ENABLE_SPI_TRANSMITTER
set_parameter_property ENABLE_SPI_TRANSMITTER WIDTH ""
set_parameter_property ENABLE_SPI_TRANSMITTER TYPE BOOLEAN
set_parameter_property ENABLE_SPI_TRANSMITTER UNITS None
set_parameter_property ENABLE_SPI_TRANSMITTER DESCRIPTION ""
set_parameter_property ENABLE_SPI_TRANSMITTER HDL_PARAMETER true
add_parameter NUMBER_OF_SENSORS INTEGER 8
set_parameter_property NUMBER_OF_SENSORS DEFAULT_VALUE 8
set_parameter_property NUMBER_OF_SENSORS DISPLAY_NAME NUMBER_OF_SENSORS
set_parameter_property NUMBER_OF_SENSORS TYPE INTEGER
set_parameter_property NUMBER_OF_SENSORS UNITS None
set_parameter_property NUMBER_OF_SENSORS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUMBER_OF_SENSORS HDL_PARAMETER true
add_parameter CLK_SPEED INTEGER 50000000
set_parameter_property CLK_SPEED DEFAULT_VALUE 50000000
set_parameter_property CLK_SPEED DISPLAY_NAME CLK_SPEED
set_parameter_property CLK_SPEED TYPE INTEGER
set_parameter_property CLK_SPEED UNITS None
set_parameter_property CLK_SPEED ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_SPEED HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end mosi_o mosi_o Output 1
add_interface_port conduit_end sck_o sck_o Output 1
add_interface_port conduit_end ss_n_o ss_n_o Output 1
add_interface_port conduit_end sync_o sync_o Output NUMBER_OF_SENSORS
add_interface_port conduit_end D_io d_io Bidir NUMBER_OF_SENSORS
add_interface_port conduit_end E_io e_io Bidir NUMBER_OF_SENSORS
add_interface_port conduit_end LED led Output 2
add_interface_port conduit_end trigger_me trigger_me Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 9
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

