# TCL File Generated by Component Editor 17.0
# Tue Nov 21 20:53:18 CET 2017
# DO NOT MODIFY


# 
# DarkRoom "DarkRoom" v1.0
#  2017.11.21.20:53:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DarkRoom
# 
set_module_property DESCRIPTION ""
set_module_property NAME DarkRoom
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME DarkRoom
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DarkRoom
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DarkRoom.v VERILOG PATH DarkRoom.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter NUMBER_OF_SENSORS INTEGER 8
set_parameter_property NUMBER_OF_SENSORS DEFAULT_VALUE 8
set_parameter_property NUMBER_OF_SENSORS DISPLAY_NAME NUMBER_OF_SENSORS
set_parameter_property NUMBER_OF_SENSORS TYPE INTEGER
set_parameter_property NUMBER_OF_SENSORS UNITS None
set_parameter_property NUMBER_OF_SENSORS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUMBER_OF_SENSORS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end mosi_o mosi_o Output 1
add_interface_port conduit_end sck_o sck_o Output 1
add_interface_port conduit_end sensor_signals_i sensor_signals_i Input NUMBER_OF_SENSORS
add_interface_port conduit_end ss_n_o ss_n_o Output 1
add_interface_port conduit_end trigger_me trigger_me Input 1
add_interface_port conduit_end sync_o sync_o Output NUMBER_OF_SENSORS


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1

