# TCL File Generated by Component Editor 18.1
# Thu Apr 09 17:59:15 CEST 2020
# DO NOT MODIFY


# 
# iCEbusControl "iCEbusControl" v1.0
# Simon Trendel 2020.04.09.17:59:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module iCEbusControl
# 
set_module_property DESCRIPTION ""
set_module_property NAME iCEbusControl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Simon Trendel"
set_module_property DISPLAY_NAME iCEbusControl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL iCEbusControl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file iCEbusControl.sv SYSTEM_VERILOG PATH iCEbusControl.sv
add_fileset_file ArmBusComs.sv SYSTEM_VERILOG PATH ArmBusComs.sv
add_fileset_file crc16.sv SYSTEM_VERILOG PATH crc16.sv
add_fileset_file iCEboardComs.sv SYSTEM_VERILOG PATH iCEboardComs.sv
add_fileset_file uart_rx.v VERILOG PATH ../uart/uart_rx.v
add_fileset_file uart_tx.v VERILOG PATH ../uart/uart_tx.v


# 
# parameters
# 
add_parameter iceboard_coms BOOLEAN true ""
set_parameter_property iceboard_coms DEFAULT_VALUE true
set_parameter_property iceboard_coms DISPLAY_NAME iceboard_coms
set_parameter_property iceboard_coms WIDTH ""
set_parameter_property iceboard_coms TYPE BOOLEAN
set_parameter_property iceboard_coms UNITS None
set_parameter_property iceboard_coms DESCRIPTION ""
set_parameter_property iceboard_coms HDL_PARAMETER true
add_parameter arm_coms BOOLEAN false ""
set_parameter_property arm_coms DEFAULT_VALUE false
set_parameter_property arm_coms DISPLAY_NAME arm_coms
set_parameter_property arm_coms WIDTH ""
set_parameter_property arm_coms TYPE BOOLEAN
set_parameter_property arm_coms UNITS None
set_parameter_property arm_coms DESCRIPTION ""
set_parameter_property arm_coms HDL_PARAMETER true
add_parameter NUMBER_OF_MOTORS INTEGER 10 ""
set_parameter_property NUMBER_OF_MOTORS DEFAULT_VALUE 10
set_parameter_property NUMBER_OF_MOTORS DISPLAY_NAME NUMBER_OF_MOTORS
set_parameter_property NUMBER_OF_MOTORS TYPE INTEGER
set_parameter_property NUMBER_OF_MOTORS UNITS None
set_parameter_property NUMBER_OF_MOTORS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUMBER_OF_MOTORS DESCRIPTION ""
set_parameter_property NUMBER_OF_MOTORS HDL_PARAMETER true
add_parameter CLOCK_FREQ_HZ INTEGER 50000000 ""
set_parameter_property CLOCK_FREQ_HZ DEFAULT_VALUE 50000000
set_parameter_property CLOCK_FREQ_HZ DISPLAY_NAME CLOCK_FREQ_HZ
set_parameter_property CLOCK_FREQ_HZ TYPE INTEGER
set_parameter_property CLOCK_FREQ_HZ UNITS None
set_parameter_property CLOCK_FREQ_HZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLOCK_FREQ_HZ DESCRIPTION ""
set_parameter_property CLOCK_FREQ_HZ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 10
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end rx rx Input 1
add_interface_port conduit_end tx tx Output 1
add_interface_port conduit_end current_average current_average Output 32

