# TCL File Generated by Component Editor 18.1
# Mon Sep 02 18:27:43 CEST 2019
# DO NOT MODIFY


# 
# RikshawControl "RikshawControl" v1.0
# Simon Trendel 2019.09.02.18:27:43
# rikshaw control
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module RikshawControl
# 
set_module_property DESCRIPTION "rikshaw control"
set_module_property NAME RikshawControl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Simon Trendel"
set_module_property DISPLAY_NAME RikshawControl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL RikshawControl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file RikshawControl.sv SYSTEM_VERILOG PATH ip/roboy_fpga_code/rikshaw/RikshawControl.sv TOP_LEVEL_FILE
add_fileset_file A1339Control.sv SYSTEM_VERILOG PATH ip/roboy_fpga_code/a133x/A1339Control.sv
add_fileset_file A1339Interface.sv SYSTEM_VERILOG PATH ip/roboy_fpga_code/interfaces/A1339Interface.sv


# 
# parameters
# 
add_parameter CLOCK_SPEED_HZ INTEGER 50000000
set_parameter_property CLOCK_SPEED_HZ DEFAULT_VALUE 50000000
set_parameter_property CLOCK_SPEED_HZ DISPLAY_NAME CLOCK_SPEED_HZ
set_parameter_property CLOCK_SPEED_HZ TYPE INTEGER
set_parameter_property CLOCK_SPEED_HZ UNITS None
set_parameter_property CLOCK_SPEED_HZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLOCK_SPEED_HZ HDL_PARAMETER true
add_parameter NUMBER_OF_SENSORS INTEGER 1
set_parameter_property NUMBER_OF_SENSORS DEFAULT_VALUE 1
set_parameter_property NUMBER_OF_SENSORS DISPLAY_NAME NUMBER_OF_SENSORS
set_parameter_property NUMBER_OF_SENSORS TYPE INTEGER
set_parameter_property NUMBER_OF_SENSORS UNITS None
set_parameter_property NUMBER_OF_SENSORS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUMBER_OF_SENSORS HDL_PARAMETER true
add_parameter SAMPLES_TO_AVERAGE INTEGER 512
set_parameter_property SAMPLES_TO_AVERAGE DEFAULT_VALUE 512
set_parameter_property SAMPLES_TO_AVERAGE DISPLAY_NAME SAMPLES_TO_AVERAGE
set_parameter_property SAMPLES_TO_AVERAGE TYPE INTEGER
set_parameter_property SAMPLES_TO_AVERAGE UNITS None
set_parameter_property SAMPLES_TO_AVERAGE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SAMPLES_TO_AVERAGE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 16
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point conduit_end_1
# 
add_interface conduit_end_1 conduit end
set_interface_property conduit_end_1 associatedClock ""
set_interface_property conduit_end_1 associatedReset ""
set_interface_property conduit_end_1 ENABLED true
set_interface_property conduit_end_1 EXPORT_OF ""
set_interface_property conduit_end_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_1 angle_miso angle_miso Input 1
add_interface_port conduit_end_1 angle_mosi angle_mosi Output 1
add_interface_port conduit_end_1 angle_sck angle_sck Output 1
add_interface_port conduit_end_1 angle_ss_n_o angle_ss_n_o Output NUMBER_OF_SENSORS
add_interface_port conduit_end_1 emergency_off emergency_off Input 1
add_interface_port conduit_end_1 throttle throttle Output 1
add_interface_port conduit_end_1 hall_sensor1 hall_sensor1 Input 1
add_interface_port conduit_end_1 hall_sensor2 hall_sensor2 Input 1
add_interface_port conduit_end_1 hall_sensor3 hall_sensor3 Input 1

