# TCL File Generated by Component Editor 19.1
# Wed May 13 18:56:59 CEST 2020
# DO NOT MODIFY


# 
# TLI4970 "TLI4970" v1.0
# Simon Trendel 2020.05.13.18:56:59
# infineon current sensor readout
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module TLI4970
# 
set_module_property DESCRIPTION "infineon current sensor readout"
set_module_property NAME TLI4970
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Simon Trendel"
set_module_property DISPLAY_NAME TLI4970
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL TLI4970
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file tli4970.v VERILOG PATH tli4970.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter NUMBER_OF_SENSORS INTEGER 2
set_parameter_property NUMBER_OF_SENSORS DEFAULT_VALUE 2
set_parameter_property NUMBER_OF_SENSORS DISPLAY_NAME NUMBER_OF_SENSORS
set_parameter_property NUMBER_OF_SENSORS TYPE INTEGER
set_parameter_property NUMBER_OF_SENSORS UNITS None
set_parameter_property NUMBER_OF_SENSORS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUMBER_OF_SENSORS HDL_PARAMETER true
add_parameter CLOCK_FREQ INTEGER 50000000
set_parameter_property CLOCK_FREQ DEFAULT_VALUE 50000000
set_parameter_property CLOCK_FREQ DISPLAY_NAME CLOCK_FREQ
set_parameter_property CLOCK_FREQ TYPE INTEGER
set_parameter_property CLOCK_FREQ UNITS None
set_parameter_property CLOCK_FREQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLOCK_FREQ HDL_PARAMETER true
add_parameter CLOCK_DIVIDER INTEGER 13
set_parameter_property CLOCK_DIVIDER DEFAULT_VALUE 13
set_parameter_property CLOCK_DIVIDER DISPLAY_NAME CLOCK_DIVIDER
set_parameter_property CLOCK_DIVIDER TYPE INTEGER
set_parameter_property CLOCK_DIVIDER UNITS None
set_parameter_property CLOCK_DIVIDER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLOCK_DIVIDER HDL_PARAMETER true
add_parameter UPDATE_FREQ INTEGER 100
set_parameter_property UPDATE_FREQ DEFAULT_VALUE 100
set_parameter_property UPDATE_FREQ DISPLAY_NAME UPDATE_FREQ
set_parameter_property UPDATE_FREQ TYPE INTEGER
set_parameter_property UPDATE_FREQ UNITS None
set_parameter_property UPDATE_FREQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property UPDATE_FREQ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 address address Input 1
add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end spi_clk spi_clk Output 1
add_interface_port conduit_end spi_cs spi_cs Output NUMBER_OF_SENSORS
add_interface_port conduit_end spi_miso spi_miso Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

